services:
  dishes:
    image: postgres:16
    environment:
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dishes
    ports:
      - "5434:5432"
    volumes:
      - dishes:/var/lib/postgresql/data
volumes:
  dishes: