spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5434/dishes
    username: ADMIN
    password: adminpassword
  datasource:
    url: jdbc:postgresql://localhost:5434/dishes
    username: ADMIN
    password: adminpassword
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: D:\IdeadProjects\OCTOBER\my-store\store-view\src\main\resources\static\images
logging:
  level:
    sql: debug
    web: debug
    org.springframework.data.r2dbc: trace
    io.r2dbc.postgresql: trace
server:
  port: 8081
#yandex:
#  oauth:
#    verification-code