spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: admin
    password: adminpassword
logging:
  level:
    sql: info
    web: trace
server:
  port: 8081