spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: ADMIN
    password: adminpassword
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: D:\images
logging:
  level:
    sql: trace
    web: trace
server:
  port: 8081
