spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/dishes
    username: ADMIN
    password: adminpassword
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: D:\IdeadProjects\OCTOBER\my-store\store-view\src\main\resources\static\images
logging:
  level:
    sql: trace
    web: trace
server:
  port: 8081
#yandex:
#  oauth:
#    verification-code